### ISSUE TITLE
TagField used in Elemental Area loses its value on blur

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe-labs/silverstripe-tagfield#252] opened 2023-07-19 02:16 UTC
## Description
TagField used in Elemental Area does not save created or added values. This issue has beed tested in v5 and v5.0.

## Steps to reproduce
- Create new Block with TagFileld;
For example, `$fields->addFieldToTab('Root.Main', TagField::create('Tags', 'Tags', BlogTag::get()));`
- Add Block to a page;
- Add new tag to the tag field;
- Click out of tag field;
- New tag disappeared;

### Related issue
- https://github.com/silverstripe/silverstripe-tagfield/issues/247

**Comment by GuySartorelli** [comment] 2023-07-19 04:49
Just as a sanity check, did you also add an appropriate relation on the block for it to save into?

**Comment by GuySartorelli** [comment] 2023-07-23 21:14
I've also tested this in 4.13 which also has this problem.

**Comment by GuySartorelli** [comment] 2023-08-21 01:32
I've tried this again in CMS 4.13 and wasn't able to reproduce so looks like it's fine there.
Merged the PR for 5.0. It'll be automatically tagged by github actions.

**Closed as completed by GuySartorelli** 2023-08-21 01:32 UTC
Labels: affects/v4, impact/medium, type/bug, affects/v5
